services:
  - type: web
    name: telegram-gpt-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
    envVars:
      - key: BOT_TOKEN
        value: <your-telegram-bot-token>
      - key: OPENAI_API_KEY
        value: <your-openai-api-key>